### ISSUE TITLE
Uploading speed Slow

### ISSUE THREAD

**Issue by 30key** [KurimuzonAkuma/pyrogram#115]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

Uploading speed slow please solve this problem

### Steps to reproduce

. 

### Code example

```python
.
```

### Logs

```shell
.
```

**Comment by Vadim-Khristenko** [comment]
Hi there,

It seems that the issue you're experiencing is not related to the library itself, but rather a problem on your end. I was able to quickly download and upload everything using Kurigram (this fork) without any issues.

Here are a few suggestions that might help resolve your problem:

Check Your Internet Speed: Ensure that your connection is stable and fast enough for your needs. If it's not, consider switching your ISP.
Ping Telegram: Test your connection to Telegram and make sure it responds without significant delays.
Use a Proxy: If you're still having issues, try using a proxy for your client.
If the problem persists, please provide a minimal code example that reproduces the issue.

@KurimuzonAkuma, I believe this issue can be closed since there are no specific details provided, and it does not appear to be a problem with the library itself.

Thank you!
